### ISSUE TITLE
Doesnt show up on insert menu

### ISSUE THREAD

**Issue by sachabarber** [jmbucknall/OLWInsertCode#1]
So I have copied things here

C:\Users\sachabarber\AppData\Local\OpenLiveWriter\app-0.6.2\plugins (also tried "Plugins")

- OpenLiveWriter.Api.dll
- WLWInsertCode.dll

restarted the open Live Writer, but don't see your menu that you are talking about

**Comment by jmbucknall** [comment]
Now fixed: essentially I'd copy/pasted from another project and hadn't changed text and identifiers. Now works as advertised.
